-- 0시부터 23시까지, 각 시간대별로 입양이 몇 건이나 발생했는지 조회

-- 0. 이 방법은 count가 0인 경우는 나오지 않는다 -> 다른 방법을 찾아야함
SELECT HOUR(DATETIME) AS HOUR, COUNT(HOUR(DATETIME)) AS COUNT
FROM ANIMAL_OUTS
GROUP BY HOUR(DATETIME)
ORDER BY HOUR(DATETIME) ASC;

-- 1. UNION 사용
SELECT TABLE_HOUR.HOUR, IFNULL(outs.COUNT, 0) AS COUNT
FROM (SELECT 0 AS HOUR
    UNION SELECT 1 UNION SELECT 2 UNION SELECT 3 UNION SELECT 4 
    UNION SELECT 5 UNION SELECT 6 UNION SELECT 7 UNION SELECT 8 
    UNION SELECT 9 UNION SELECT 10 UNION SELECT 11 UNION SELECT 12
    UNION SELECT 13 UNION SELECT 14 UNION SELECT 15 UNION SELECT 16 
    UNION SELECT 17 UNION SELECT 18 UNION SELECT 19 UNION SELECT 20 
    UNION SELECT 21 UNION SELECT 22 UNION SELECT 23) AS TABLE_HOUR
LEFT JOIN (SELECT HOUR(DATETIME) AS HOUR, COUNT(HOUR(DATETIME)) AS COUNT
    FROM ANIMAL_OUTS
    GROUP BY HOUR(DATETIME)) AS outs
ON TABLE_HOUR.HOUR = outs.HOUR

-- 2. 변수 사용
SET @VALUE_HOUR = -1;
SELECT (@VALUE_HOUR := @VALUE_HOUR + 1) AS HOUR, (
    SELECT COUNT(HOUR(DATETIME))
    FROM ANIMAL_OUTS
    WHERE HOUR(DATETIME) = @VALUE_HOUR) AS COUNT
FROM ANIMAL_OUTS
WHERE @VALUE_HOUR < 23;