-- 우유와 요거트를 동시에 구입한 장바구니의 아이디를 조회

SELECT MILK.CART_ID
FROM (SELECT DISTINCT CART_ID
    FROM CART_PRODUCTS
    WHERE NAME = 'Milk') AS MILK
INNER JOIN (SELECT DISTINCT CART_ID
    FROM CART_PRODUCTS
    WHERE NAME = 'Yogurt') AS YOGURT
ON MILK.CART_ID = YOGURT.CART_ID;