-- 보호 시작일보다 입양일이 더 빠른 동물의 아이디와 이름을 조회

SELECT ins.ANIMAL_ID, ins.NAME
FROM ANIMAL_INS AS ins
LEFT JOIN ANIMAL_OUTS AS outs 
ON ins.ANIMAL_ID = outs.ANIMAL_ID
WHERE ins.DATETIME > outs.DATETIME
ORDER BY ins.DATETIME ASC;